"""
====================
RUN END-TO-END PIPELINE
====================
End-to-end pipeline: clear Elasticsearch index → preprocessing → topic modeling.

Steps:
  1. Clear the Elasticsearch index (if running)
  2. Preprocess sample_posts.json (always)
  3. Preprocess noise_posts.json (if it exists — generated by generate_noise.py)
  4. Train the topic model

Once you have run this, don't forget to clear the cache in the demo app to see the new results.
"""

from pathlib import Path

from solutions.preprocess import INPUT_FILEPATH, OUTPUT_FILEPATH, PreprocessingPipeline
from solutions.topic_model import TopicModeler
from src.config import REPO

NOISE_FILEPATH = REPO / "sample_noise.json"


def pipeline(use_input: Path = INPUT_FILEPATH, use_output: Path = OUTPUT_FILEPATH):
    """Run preprocessing then topic modeling in sequence."""

    print(f"Running preprocessing pipeline on {use_input}...")
    PreprocessingPipeline(input_filepath=use_input, output_filepath=use_output).run()
    print("Preprocessing complete.\n")

    print("Running topic modeling pipeline...")
    TopicModeler().run()
    print("Topic modeling complete.\n")

    print("Pipeline complete. Run: `uv run streamlit run app.py` to start the demo app.")


if __name__ == "__main__":
    NOISE_INPUT: Path = NOISE_FILEPATH
    pipeline()

    # --- SWITCH TO NOISE FILEPATH TO ADD RANDOM POSTS TO THE MIX ---

    # pipeline(use_input=NOISE_INPUT)
