"""
====================
RUN END-TO-END PIPELINE
====================
End-to-end pipeline: clear Elasticsearch index → preprocessing → topic modeling.

Steps:
  1. Clear the Elasticsearch index (if running)
  2. Preprocess sample_posts.json (always)
  3. Preprocess noise_posts.json (if it exists — generated by generate_noise.py)
  4. Train the topic model

Once you have run this, don't forget to clear the cache in the demo app to see the new results.
"""

from solutions.es_index import delete_index, get_es_client
from solutions.preprocess import INPUT_FILEPATH, OUTPUT_FILEPATH, PreprocessingPipeline
from solutions.topic_model import TopicModeler
from src.config import REPO

### EXERCISE ###
# Path to posts generated with additional random posts.
# Replace INPUT_FILEPATH with NOISE_FILEPATH  in the PreprocessingPipeline below
# This will add additional posts on random topics to the topic model training.
# Explore how this affects search results!

NOISE_FILEPATH = REPO / "sample_noise.json"


def pipeline():
    """Run preprocessing then topic modeling in sequence."""

    print("Deleting existing Elasticsearch index (if any)...")
    es_client = get_es_client()
    delete_index(client=es_client)

    print("Running preprocessing pipeline on sample_posts.json...")
    PreprocessingPipeline(input_filepath=INPUT_FILEPATH, output_filepath=OUTPUT_FILEPATH).run()
    print("Preprocessing complete.\n")

    print("Running topic modeling pipeline...")
    TopicModeler().run()
    print("Topic modeling complete.\n")

    print("Pipeline complete. Run: `uv run streamlit run app.py` to start the demo app.")


if __name__ == "__main__":
    pipeline()
