"""
====================
RUN END-TO-END PIPELINE
====================
End-to-end pipeline: clear Elasticsearch index → preprocessing → topic modeling.

Steps:
  1. Clear the Elasticsearch index (if running)
  2. Preprocess sample_posts.json (always)
  3. Preprocess noise_posts.json (if it exists — generated by generate_noise.py)
  4. Train the topic model

Once you have run this, don't forget to clear the cache in the demo app to see the new results.
"""

from src.config import OUTPUT
from src.es_index import delete_index, get_es_client
from src.preprocess import INPUT_FILEPATH, PreprocessingPipeline
from src.topic_model import TopicModeler

NOISE_FILEPATH = OUTPUT / "noise_posts.json"


def pipeline():
    """Run preprocessing then topic modeling in sequence."""

    print("Deleting existing Elasticsearch index (if any)...")
    es_client = get_es_client()
    delete_index(client=es_client)

    print("Running preprocessing pipeline on sample_posts.json...")
    PreprocessingPipeline(input_filepath=INPUT_FILEPATH).run()
    print("Preprocessing complete.\n")

    if NOISE_FILEPATH.exists():
        print("noise_posts.json found — preprocessing noise posts...")
        PreprocessingPipeline(input_filepath=NOISE_FILEPATH).run()
        print("Noise preprocessing complete.\n")
    else:
        print("No noise_posts.json found — skipping noise preprocessing.")

    print("Running topic modeling pipeline...")
    TopicModeler().run()
    print("Topic modeling complete.\n")

    print("Pipeline complete. Run: `uv run streamlit run app.py` to start the demo app.")


if __name__ == "__main__":
    pipeline()
